apiVersion: v1
kind: Service # a way for the outside world to reach the Pods
metadata:
  # the name of our external Service
  name: external-service
spec:
  # Service ports
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  # Points to external name
  type: ExternalName
  # the external url
  externalName: jonbcampos.com/wp-json/wp/v2/posts
  selector:
    app: kubernetes-series