apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-pods
  labels:
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    matchLabels:
      name: daemonset-pods
  template:
    metadata:
      labels:
        name: daemonset-pods